apiVersion: v1
kind: Service
metadata:
  name: customer-node-port
spec:
  type: NodePort
  ports:
    - port: 8199
      targetPort: 8184
      nodePort: 31513
  selector:
    app: customer-deployment
