apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  selector:
    app: order-deployment
  ports:
    - name: order-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""