apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: default
  labels:
    app: restaurant-service
spec:
  selector:
    app: restaurant-deployment
  ports:
    - name: restaurant-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: ""
