kubectl delete -f order-deployment-local.yml
kubectl delete -f order-deployment-service-local.yml
kubectl delete -f payment-deployment-local.yml
kubectl delete -f payment-deployment-service-local.yml
kubectl delete -f restaurant-deployment-local.yml
kubectl delete -f restaurant-deployment-service-local.yml
kubectl delete -f customer-deployment-local.yml
kubectl delete -f customer-deployment-service-local.yml
kubectl delete -f order-node-port.yml
kubectl delete -f customer-node-port.yml